# Generated by Django 3.0 on 2020-06-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0002_auto_20200612_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='letting',
            name='title',
            field=models.TextField(default='hi', max_length=256),
            preserve_default=False,
        ),
    ]
