# Generated by Django 3.0 on 2020-06-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0003_letting_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='letting',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
